# Generated by Django 4.0.6 on 2022-07-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
