# Generated by Django 4.0.6 on 2022-07-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_slug_product_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
