# Generated by Django 4.0.4 on 2022-08-12 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 12, 15, 52, 4, 154556)),
        ),
    ]
